apiVersion: v1
kind: Service
metadata:
  name: springboot-helloworld-node-port
spec:
  type: NodePort
  ports:
    - port: 8580
      targetPort: 8080
      nodePort: 30000
  selector:
    QUALQUER_COISA: springboothelloworld